language: node_js
os:
- linux
node_js:
- 8
before_install:
- npm i npm@latest -g
env:
- PACKAGE_VERSION=$(npm run -s version)
script:
- npm test
- npm run build
deploy:
  - provider: npm
    on:
      tags: true
    email:
      secure: rDxSUhcMBUzUu0soB7Wy0mDzbQdaFTpQzms4X1PCWfXxIeJU/2p55HXJtJQcySwa5JWv43ZtV2h0mb2fr0vJN7PG9CMPKHrE9SM6xPUckL3OoKMtmHsExMsorGZ5NLx0X0JSIPk2AGGVqnVAAJ9n2bnklIBGV9YXYs9lM5wVV9d5l5HU80jtDWKG002LS9l4v3GDbzZUMouIb9LSA46BSnltw8nfY926IVIng1kXp4/1n6Q7Cv2tCzmnIf2zrYGMNbBBsR3oZiw2yR6ZKNFOliqp0tV/EW1zpPN0jhzzUDAd7O5lFPMniQFHBFtJJJaGTgDSxSRkd2aIFq86BO70wu9d9HyCxPIMlB7nmin23Vt3na41S0AFjcBSImN8v10SSNjVOGTupU9O/rHjUi9kmZyooq27TfqTUtgdiLVn8708Nq+gKnnhyJzNDuo0Nc1fnLW3rI9A8YbyLOtQAGD7aL1awFsa4x3AmCnGXgzgqsHvd4mDm/kmdXGBLfmywpReWys7hfQvtoRz8KT9BQEcBO7WNT1XgJgf7TZXx/8qUDMG/2LJmxlT7q+vkzv6PvxcQUbAFsVvIX6HsJm4gzHQUVEstodndymLVoWISH1Ocxl3QPEFYCKr7tFo8A3M81FCxsZ31cTx4vEyzemh2N2Wh0v7ZFrDUD2QVB6s9oOGQ4E=
    api_key:
      secure: Mkx+Pew15o4ciM75v7B50gRATkFXEU7gsfFoFxjL2RlRIH8En++fcJAm4ACePLceF0xQ/LcMW+Mm/LspvRQPMi7YpE0GVDTYrIs14XrQTgoQK1S6bk2tJkNDP5vjq1wexGZrMTm+MKVOOKh8OPpEggI0E3qAiX5swgcj5v02LSLXGJ1tWdB1CahSMBB3WwxhPwgPoMLrb/sxZRhbrbcp4cww/PEwOeXZAIk4pvoD6mx8C8d5O+YQ5ixP2kRrvggdVHK9jFAD3LW1koAMZt57gdVG29ZOo0x6HJhAyk+oK2nu/YmVW5b4JT81YNdP7ECdS6QHjtgj5Lehlm74D68HMa1l0qIjbo9neaneGZfdCoEu5w8e7lU+BELz4ZnZBXfmp+Shp6YmtTl5GMsMTU1sKSoiGF4tOzmyYhvjZkYhQ6DJXWfmr870GzJQpJ7mYDebnhkdKnoUIAoYaw1HUdJgv6jJOPeHhYBE7SoNHba1I8XCRVV4xLY6Lh8O7xgLqAmuQvRE1Aq07XXQI2+xAreldqMcKTEZ5YMW26vZbpBiMJMOZnA2YQJbOHTKC32eVPpCSreLODoExnn7EtqEa5POflH1SEKRXywid8KCLDIlgpuFcWDLNrkUz5EHlOvFOBFdowTO66mxHiw9DRr0bbYpSiaI3w2AS6wOuK7yCItAWDA=
    skip_cleanup: true
  - provider: s3
    on:
      tags: true
    access_key_id:
      secure: Qc2pnp2dlMySDSTRYoGcfwsr3ZFi3GCWku8kVeYRv8Zu0cCPmRZZh/wEwERmkbXmeTVV0kP16wsrsFAsvza5BkLaiT6GvWcbN/J45ffyeD7YjheaFbefwLvi5B3vLkMesCFDnddvQbWFTBagpFHdglXEqI2cO7lVuKdeCGTXzgeE+ed7tdTJgl+r2XrWfiPTxnH514hUp+Kub8aCrlWM3PGLkFGKNXfWlY6bufhMULyq5U2SS8mklnHlQlXc7hvhJ1PmdAxlbdnRTqK5wRCT4GaI4Bg/pSc7h6Tjmc9mnHpoQga0T0ii6RjClS2GC5CGCiRJSbiISRctBkewb+VQeNemPwaajyFQ3lfN50oh3E20pwde0Wd730LZFR3L2Jh5OewfsJ9h3CrmuKpNuuF7cm+6LKvXc23Qcn1h6eQ5uIY/Nqi6UTLKyUsVpkzBejpjhoq5MVVfsHuJyACAeqGxaPU8+q0D8wmuhEougN7gwWaDd3kOmvfJVS21IJMD6qqoBxZPCO/qNeIoCIBwUq1+g0WMC8zyIjGbEBBiJwMJNMq8ydLQpxrsOPkR2pZmx0IZrzksGil8jyJRUyPx9OBafuME4B2CptwZ4X8CejSLqRmX0jV0FSq/bwEjTIyzYxnBgqulgsUM9Ie3Mj3gxpr1vHakg425DCdiY2IaT3AsOYc=
    secret_access_key:
      secure: E9wLXYmzlSRnrVczxLdHv4fbuwkuZmtv+LT03diLgJhlfk80/LSU0PBcgnl+87oMq/W18TzyXc1O8sT9zgFNiiAjKdMLwbkJb9iySjmvflVA/i4P/ppJW6c9DfGOoSAZZ8Q0yrClY2qGd10IVsydzehddYrw5C7Cz5I643fyvHT9vuCqB1U8LV0taVhpAD564D0oHAR3jLW8dPMEXSK99n2OaEGObMwN81dXl4UGww2kUh6aU2Sh95zxep1Kk6YrGrb23nr3KHNuICpFe8IjrQC/OXP+mLCohWbdwwIWedZmdicuRtyc3xkDLIe1GVhtuEEFGFLjLMbT9L1XxH93jmQOeF8Hnl5QcydZ2O2cTdoQWrj46gM9LROOpXscUR8h24HyDshcDc3k9yStr0Rli3RNiL5IsZS06oxj6GRYUr0kTj2xeDkIqjg7agtMTFNq/rO0cyZ1mEqpmTqgqFbEtLUZ+bYLpvTE1Z6w0VJEubI05Rp02FoRuapd9iQ1woUIj/zP06bggc19NR0OFnF8cKLjT6yeJNXw38cGVqfzS/3gDYXufijF/p+oryY5cHXK4t94DN0Xb66ymUvreg83bpJArQkUpzj4XYUcBVw7NZJNv1lOKzwKWsfGChxRXITFGxO7zBc46qSNrF35YaLMxqDOMmTNoSWto7nA0CMXFZM=
    bucket: bitclock-public
    skip_cleanup: true
    local-dir: dist
    upload-dir: $PACKAGE_VERSION
    acl: public_read
