language: node_js
os:
- linux
- osx
node_js:
- 4
- 6
- stable
before_install:
- npm i npm@latest -g
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: rDxSUhcMBUzUu0soB7Wy0mDzbQdaFTpQzms4X1PCWfXxIeJU/2p55HXJtJQcySwa5JWv43ZtV2h0mb2fr0vJN7PG9CMPKHrE9SM6xPUckL3OoKMtmHsExMsorGZ5NLx0X0JSIPk2AGGVqnVAAJ9n2bnklIBGV9YXYs9lM5wVV9d5l5HU80jtDWKG002LS9l4v3GDbzZUMouIb9LSA46BSnltw8nfY926IVIng1kXp4/1n6Q7Cv2tCzmnIf2zrYGMNbBBsR3oZiw2yR6ZKNFOliqp0tV/EW1zpPN0jhzzUDAd7O5lFPMniQFHBFtJJJaGTgDSxSRkd2aIFq86BO70wu9d9HyCxPIMlB7nmin23Vt3na41S0AFjcBSImN8v10SSNjVOGTupU9O/rHjUi9kmZyooq27TfqTUtgdiLVn8708Nq+gKnnhyJzNDuo0Nc1fnLW3rI9A8YbyLOtQAGD7aL1awFsa4x3AmCnGXgzgqsHvd4mDm/kmdXGBLfmywpReWys7hfQvtoRz8KT9BQEcBO7WNT1XgJgf7TZXx/8qUDMG/2LJmxlT7q+vkzv6PvxcQUbAFsVvIX6HsJm4gzHQUVEstodndymLVoWISH1Ocxl3QPEFYCKr7tFo8A3M81FCxsZ31cTx4vEyzemh2N2Wh0v7ZFrDUD2QVB6s9oOGQ4E=
  api_key:
    secure: Mkx+Pew15o4ciM75v7B50gRATkFXEU7gsfFoFxjL2RlRIH8En++fcJAm4ACePLceF0xQ/LcMW+Mm/LspvRQPMi7YpE0GVDTYrIs14XrQTgoQK1S6bk2tJkNDP5vjq1wexGZrMTm+MKVOOKh8OPpEggI0E3qAiX5swgcj5v02LSLXGJ1tWdB1CahSMBB3WwxhPwgPoMLrb/sxZRhbrbcp4cww/PEwOeXZAIk4pvoD6mx8C8d5O+YQ5ixP2kRrvggdVHK9jFAD3LW1koAMZt57gdVG29ZOo0x6HJhAyk+oK2nu/YmVW5b4JT81YNdP7ECdS6QHjtgj5Lehlm74D68HMa1l0qIjbo9neaneGZfdCoEu5w8e7lU+BELz4ZnZBXfmp+Shp6YmtTl5GMsMTU1sKSoiGF4tOzmyYhvjZkYhQ6DJXWfmr870GzJQpJ7mYDebnhkdKnoUIAoYaw1HUdJgv6jJOPeHhYBE7SoNHba1I8XCRVV4xLY6Lh8O7xgLqAmuQvRE1Aq07XXQI2+xAreldqMcKTEZ5YMW26vZbpBiMJMOZnA2YQJbOHTKC32eVPpCSreLODoExnn7EtqEa5POflH1SEKRXywid8KCLDIlgpuFcWDLNrkUz5EHlOvFOBFdowTO66mxHiw9DRr0bbYpSiaI3w2AS6wOuK7yCItAWDA=
  skip_cleanup: true
